### ISSUE TITLE
ACS-74 Stealth Cloak breaks on loading

### ISSUE THREAD

**Issue by MarsM0nd** [Noctifer-de-Mortem/nocts_cata_mod#274]
A freshly spawned stealth cloak works as intended, but upon reloading, the invisibility is lost. Seems the ench_effect is not saved (see [CDDA#49334](https://github.com/CleverRaven/Cataclysm-DDA/issues/49334)). This is for DDA, not sure if BN is affected
A workaround/fix seems to be moving the whole passive_effects in it's own enchantment and just referencing the ID as passive_effects:
```json
{
    "id": "ench_stealth_cloak",
    "type": "enchantment",
    "has": "WORN",
    "condition": "ALWAYS",
    "values": [
      { "value": "SPEED", "add": -20 },
      { "value": "STRENGTH", "add": -4 },
      { "value": "DEXTERITY", "add": -4 }
    ],
    "ench_effects": [ { "effect": "invisibility", "intensity": 1 } ]
  },
  "relic_data": {
      "passive_effects": [ {"id": "ench_stealth_cloak"} ]
    },```

**Comment by chaosvolt** [comment]
Why am I not surprised, always something like this with DDA. I just tested it with the BN version and it works fine, so this is likely a Korg code error again.

I'll implement the workaround in a bit.

**Comment by ZhilkinSerg** [comment]
> 
> 
> Why am I not surprised, always something like this with DDA. I just tested it with the BN version and it works fine, so this is likely a Korg code error again.
> 
> I'll implement the workaround in a bit.

Ofc, it is working fine in BN - it was you who created https://github.com/cataclysmbnteam/Cataclysm-BN/issues/186 several months ago and https://github.com/cataclysmbnteam/Cataclysm-BN/pull/386 was raised by @olanti-p to fix the issue.

I understand you are banned from CDDA project and could not report the same thing there, but you could've asked someone to warn CDDA team (say, ping @korggent or @zhilkinserg in https://github.com/cataclysmbnteam/Cataclysm-BN/issues/186) instead of holding a grudge each and every time.

**Comment by I-am-Erk** [comment]
> ping KorGgenT

Don't do that. Ping @ZhilkinSerg , often and repeatedly. He loves being pung.

**Comment by chaosvolt** [comment]
You're misrepresenting the problem. That issue was specifically for intermittent_activation, which already had a corresponding issue reported on DDA. I didn't not go through Olani's PR to figure out exactly what all was fixed, nor did I go source-diving to see what all might be useful for porting over to DDA.

I was literally only this morning made aware of there being yet ANOTHER property being broken by save-load, via this issue. I haven't had time to pester anyone to go make a bug report, as I've been fixing more important things since I first got online two hours ago.

Do not bring your hostility into spaces where it is unwelcome and off-topic to what is actually being discussed. That goes double to @I-am-Erk, shitposts suggesting someone should repeatedly ping another user are not useful.

**Comment by olanti-p** [comment]
> > Why am I not surprised, always something like this with DDA. I just tested it with the BN version and it works fine, so this is likely a Korg code error again.
> > I'll implement the workaround in a bit.
> 
> Ofc, it is working fine in BN - it was you who created cataclysmbnteam/Cataclysm-BN#186 several months ago and cataclysmbnteam/Cataclysm-BN#386 was raised by @olanti-p to fix the issue.

Since I've been pinged, I'll add my 2 cents.

cataclysmbnteam/Cataclysm-BN#186 (intermittent activation) and https://github.com/CleverRaven/Cataclysm-DDA/issues/49334 (effects-from-enchantments) are 2 completely different bugs, and both are still present in DDA.

In that PR, I've fixed 186 and along the way found and fixed 49334. I didn't think much about the latter at that time and assumed the code to be lost during porting, but we (CV and I) did discuss 186 on the modding discord, and pinged @Maleclypse about it (since @Maleclypse and @KorGgenT were the ones who worked on it in https://github.com/CleverRaven/Cataclysm-DDA/pull/42885).

Maleclypse seemed like a neutral party that would be interested in the fix, so I didn't bother bothering other people.

**Comment by Maleclypse** [comment]
> > > Why am I not surprised, always something like this with DDA. I just tested it with the BN version and it works fine, so this is likely a Korg code error again.
> > > I'll implement the workaround in a bit.
> > 
> > 
> > Ofc, it is working fine in BN - it was you who created [cataclysmbnteam/Cataclysm-BN#186](https://github.com/cataclysmbnteam/Cataclysm-BN/issues/186) several months ago and [cataclysmbnteam/Cataclysm-BN#386](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/386) was raised by @olanti-p to fix the issue.
> 
> Since I've been pinged, I'll add my 2 cents.
> 
> [cataclysmbnteam/Cataclysm-BN#186](https://github.com/cataclysmbnteam/Cataclysm-BN/issues/186) (intermittent activation) and [CleverRaven/Cataclysm-DDA#49334](https://github.com/CleverRaven/Cataclysm-DDA/issues/49334) (effects-from-enchantments) are 2 completely different bugs, and both are still present in DDA.
> 
> In that PR, I've fixed 186 and along the way found and fixed 49334. I didn't think much about the latter at that time and assumed the code to be lost during porting, but we (CV and I) did discuss 186 on the modding discord, and pinged @Maleclypse about it (since @Maleclypse and @KorGgenT were the ones who worked on it in [CleverRaven/Cataclysm-DDA#42885](https://github.com/CleverRaven/Cataclysm-DDA/pull/42885)).
> 
> Maleclypse seemed like a neutral party that would be interested in the fix, so I didn't bother bothering other people.

Yes, you did ping me and I remember looking at it and then irl happened I think.
